# Numpy Crash Course

In [4]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [50]:
import sys 
sys.version

'3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]'

## Creating Arrays

In [51]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [52]:
type(my_list)

list

In [53]:
arr = np.array(my_list) 

In [54]:
arr

array([0, 1, 2, 3, 4, 5])

In [55]:
type(arr)

numpy.ndarray

In [56]:
type(my_list)

list

In [57]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [58]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
np.arange(3.0)  

array([0., 1., 2.])

In [60]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [62]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [63]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int32)

In [64]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [65]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [66]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [67]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int32)

In [68]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [69]:
np.arange(10,10) 

array([], dtype=int32)

In [70]:
np.arange()

TypeError: arange() requires stop to be specified.

In [71]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [72]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [73]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [74]:
np.zeros(3) # parameter  tunning 

array([0., 0., 0.])

In [75]:
np.zeros(5, dtype=int) # hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [76]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [77]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [78]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [79]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [80]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [81]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [83]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [85]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [86]:
n

(6, 7)

In [87]:
n1

(6, 8)

In [88]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [89]:
np.ones(3)

array([1., 1., 1.])

In [90]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [91]:
np.ones(4)

array([1., 1., 1., 1.])

In [92]:
n

(6, 7)

In [93]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [94]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [95]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [96]:
np.twos((2,3)) 

AttributeError: module 'numpy' has no attribute 'twos'

In [97]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [98]:
np.ones(2)

array([1., 1.])

In [99]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [100]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [101]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [102]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [103]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [104]:
range(5)

range(0, 5)

In [105]:
r = range(5)
r

range(0, 5)

In [106]:
for i in r:
    print(i)

0
1
2
3
4


In [107]:
list(range(5))

[0, 1, 2, 3, 4]

In [108]:
range(1,10)

range(1, 10)

In [ ]:
list(range(1,10))

In [109]:
list(range(1,10,3))

[1, 4, 7]

In [110]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [111]:
rand(3,2)

NameError: name 'rand' is not defined

In [112]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [116]:
np.random.rand(5)

array([0.28400683, 0.70190011, 0.02948273, 0.53657208, 0.04708896])

In [119]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [126]:
np.random.rand(2,4)

array([[0.73794061, 0.85933955, 0.05963442, 0.24872975],
       [0.49333625, 0.65918332, 0.40605833, 0.90842629]])

In [134]:
np.random.randint(2,4)

3

In [139]:
np.random.randint(2,20) # 2nd argument is exlusive 

4

In [141]:
np.random.randint(0,1) 

0

In [145]:
np.random.randint(10,20,5)

array([16, 10, 12, 15, 17])

In [146]:
np.random.randint(1,6,4)

array([4, 1, 4, 4])

In [147]:
np.random.rand(3)

array([0.55450669, 0.09294257, 0.36083382])

In [148]:
np.random.randint(1)  

0

In [149]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [150]:
np.random.randint(-30,20,10) 

array([-26, -27, -30,  -9,  -3,  -9, -26,   2,   1, -12])

In [ ]:
np.random.randint(20,30,10) 

In [ ]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

In [265]:
np.random.randint(10,21,3)

array([12, 20, 17])

In [151]:
np.random.randint(1,12,10)

array([ 3,  7,  4,  4, 11, 11,  6,  9, 11,  1])

In [152]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[19, 35, 28, 11, 13, 35, 33, 19, 18, 27],
       [15, 28, 33, 16, 25, 21, 19, 15, 27, 35],
       [30, 11, 32, 23, 23, 38, 25, 13, 35, 14],
       [17, 24, 15, 22, 14, 13, 11, 38, 26, 13],
       [11, 21, 25, 11, 13, 15, 20, 24, 33, 23],
       [25, 12, 23, 29, 24, 28, 19, 29, 20, 29],
       [27, 30, 33, 13, 29, 37, 38, 25, 36, 28],
       [10, 20, 29, 19, 11, 27, 17, 14, 32, 39],
       [38, 23, 12, 22, 30, 28, 35, 17, 31, 17],
       [26, 25, 33, 25, 16, 24, 16, 25, 19, 37]])

In [153]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[77,  3, 76, 53, 28, 39, 81, 69, 90, 15, 28, 78],
       [43,  7, 29, 42, 82,  2, 18, 39, 32, 96, 26, 91],
       [54, 93, 31, 76, 39, 75, 60, 67, 12, 81, 78, 22],
       [10, 94, 23, 13, 57, 36, 74, 33, 35, 75, 11, 77],
       [86, 95, 61, 70, 14, 89,  4,  1, 74,  9, 20, 99],
       [20, 68, 66, 44, 56, 54, 40, 55, 10, 14, 55, 64],
       [35, 77, 79,  1, 96, 92, 77, 66, 55, 53,  4, 77],
       [64, 79, 12, 35, 20, 44, 51, 11, 54,  1, 99, 82],
       [ 2, 87, 50, 10, 19,  6, 65, 24, 20, 52,  6, 86],
       [85, 26, 49, 80, 54, 52, 49, 44, 91,  1, 16,  2],
       [44, 30, 21, 95, 33,  6, 65, 99, 67, 72, 81, 20],
       [19, 37, 12, 85, 69, 48, 61, 31, 35, 39, 10, 23]])

In [159]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [161]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [6]:
b = np.random.randint(10,20,(5,4))
b

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [163]:
type(b)

numpy.ndarray

In [7]:
b

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [11]:
b[:] 

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [15]:
b[1:3]

array([[14, 15, 11, 10],
       [11, 16, 13, 10]])

In [12]:
b

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [18]:
b[1,2]

11

In [169]:
b

array([[19, 11, 11, 17],
       [18, 12, 19, 12],
       [15, 12, 17, 11],
       [10, 16, 13, 19],
       [16, 15, 18, 19]])

In [171]:
b[1,3]

12

In [172]:
b[1,-1]

12

In [19]:
b

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [21]:
b[2:3]

array([[11, 16, 13, 10]])

In [22]:
b

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [23]:
b[0:-2] 

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10]])

In [24]:
b

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [25]:
b[0,2] 

17

In [26]:
b

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [27]:
b[-5,-3] 

15

In [28]:
b

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [29]:
b[-4,2] 

11

In [30]:
np.random.randint(10,20,(4,4))

array([[16, 10, 16, 15],
       [15, 13, 19, 17],
       [13, 16, 13, 13],
       [11, 17, 15, 12]])

In [31]:
b 

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [32]:
b[-4,-2]

11

In [33]:
b

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

In [34]:
b[-4:2] 

array([[14, 15, 11, 10]])

In [35]:
b[:]

array([[15, 15, 17, 16],
       [14, 15, 11, 10],
       [11, 16, 13, 10],
       [14, 14, 12, 11],
       [18, 18, 18, 19]])

## Operations

In [36]:
a = np.random.randint(10,20,10)
a

array([18, 15, 16, 10, 17, 11, 11, 12, 13, 13])

In [37]:
id(a)

1954286824176

In [38]:
arr

NameError: name 'arr' is not defined

In [39]:
arr2 = np.random.randint(0,100,(10,10))

In [198]:
arr2

array([[68, 34, 21, 54, 69, 99, 95, 39, 50, 49],
       [71, 73, 67, 76, 25, 84, 31, 25, 17, 12],
       [82, 76, 23, 71, 48, 82, 59,  7, 95, 51],
       [75, 95, 22, 30, 79, 14, 24, 70, 98, 27],
       [63, 69, 30,  0, 57, 86, 81, 36, 51, 74],
       [30, 44, 74,  3, 28,  5,  4, 67, 46, 33],
       [19, 76, 83, 66, 24, 99, 66, 77, 86, 67],
       [77, 57, 41, 64, 27, 32,  1, 26, 12, 77],
       [ 0, 15, 61, 43, 48, 16, 39,  5, 25, 36],
       [47, 50, 30, 31,  4, 39, 71, 95, 43, 98]])

In [ ]:
arr

In [199]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [200]:
arr

array([0, 1, 2, 3, 4, 5])

In [201]:
arr[:4] 

array([0, 1, 2, 3])

In [40]:
arr2[:]

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [68, 17, 85, 12, 25,  5, 18, 91, 47, 34]])

In [41]:
arr2[0:5] 

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57]])

In [42]:
arr2

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [68, 17, 85, 12, 25,  5, 18, 91, 47, 34]])

In [43]:
arr2[1,4] 

47

In [44]:
arr2

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [68, 17, 85, 12, 25,  5, 18, 91, 47, 34]])

In [45]:
arr2[-5,5] 

94

In [46]:
arr2[-5,-5] 

94

In [47]:
arr2

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [68, 17, 85, 12, 25,  5, 18, 91, 47, 34]])

In [48]:
arr2[-5,-5]

94

In [49]:
arr2

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [68, 17, 85, 12, 25,  5, 18, 91, 47, 34]])

In [50]:
arr2[-1,-2]

47

In [51]:
arr2

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [68, 17, 85, 12, 25,  5, 18, 91, 47, 34]])

In [52]:
arr2[::-1]

array([[68, 17, 85, 12, 25,  5, 18, 91, 47, 34],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [22, 33, 62, 67, 43, 76, 26, 48,  1, 18]])

In [53]:
arr2

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [68, 17, 85, 12, 25,  5, 18, 91, 47, 34]])

In [54]:
arr2[::-2] 

array([[68, 17, 85, 12, 25,  5, 18, 91, 47, 34],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47]])

In [55]:
arr2

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [68, 17, 85, 12, 25,  5, 18, 91, 47, 34]])

In [56]:
arr2[::-3]

array([[68, 17, 85, 12, 25,  5, 18, 91, 47, 34],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [22, 33, 62, 67, 43, 76, 26, 48,  1, 18]])

In [57]:
arr2

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40],
       [16, 45, 15, 67, 62, 86, 25, 32, 22, 26],
       [10, 39, 85, 49, 19, 99,  2, 13, 28, 83],
       [68, 17, 85, 12, 25,  5, 18, 91, 47, 34]])

In [58]:
arr2[:-3] 

array([[22, 33, 62, 67, 43, 76, 26, 48,  1, 18],
       [ 3, 76, 74, 91, 47, 44, 18, 89, 56, 47],
       [57, 63, 13, 58, 76, 13, 74, 38, 11, 25],
       [96, 20, 54, 95,  1, 22, 74, 63, 56, 68],
       [47, 34, 80, 60,  7, 21, 30,  9,  3, 57],
       [87, 99, 53, 53, 21, 94, 26, 79, 18, 76],
       [60,  6,  9, 53, 46, 42,  3, 67, 40, 40]])

In [217]:
arr

array([0, 1, 2, 3, 4, 5])

In [218]:
arr.max() 

5

In [219]:
arr.min()

0

In [220]:
arr

array([0, 1, 2, 3, 4, 5])

In [221]:
arr.mean()

2.5

In [222]:
arr

array([0, 1, 2, 3, 4, 5])

In [223]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [224]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

# Without work on import* can you please find the median, mode)

In [225]:
arr

array([0, 1, 2, 3, 4, 5])

In [226]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr.reshape(6,1)  

In [ ]:
arr.reshape(1,6) 

In [ ]:
arr

In [ ]:
arr.reshape(2,4) 

In [ ]:
arr

In [ ]:
arr.reshape(2,3,order='C') 

In [ ]:
arr.reshape(2,3,order='F') # print element with fortran 

In [ ]:
arr.reshape(2,3,order='A') # A almost give you c type output 

In [ ]:
arr

In [ ]:
arr.reshape(2,3)

In [ ]:
arr.reshape(1,4)  

In [ ]:
arr.reshape(1,6)  

In [ ]:
arr.reshape(6,1)  

In [ ]:
arr.reshape(2,6) 

In [ ]:
arr.reshape(3,3) 

In [ ]:
arr

In [ ]:
arr.reshape(3,2)  

## Indexing

In [62]:
mat = np.arange(0,100).reshape(10,10) 

In [228]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
row = 4
col = 5

In [231]:
col

5

In [232]:
row

4

In [63]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
mat[row,col] 

45

In [64]:
mat[4,5] 

45

In [65]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
col = 6

In [67]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
mat[6] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [240]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [242]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [244]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [70]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [72]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [73]:
row

4

In [74]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [76]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [77]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [78]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [80]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [82]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [83]:
row

4

In [84]:
col

6

In [85]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [86]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
mat[1,4]

14

In [88]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [90]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [92]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [95]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [97]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [98]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [99]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [ ]:
mat

In [ ]:
mat[0:10]

In [100]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [101]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [102]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [103]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [105]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [106]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [107]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [108]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [109]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
mat

In [110]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [111]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [112]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [113]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [245]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [117]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [118]:
mat[0,1]

1

In [119]:
mat[1,6]

16

In [120]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [121]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [122]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [123]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [124]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [125]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [126]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [127]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [128]:
mat[3,5]

35

In [266]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [267]:
mat[1:2,2:4] 

array([[12, 13]])

In [247]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [130]:
mat[2:3,2:3] 

array([[22]])

In [249]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [268]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [250]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [ ]:
mat

In [ ]:
mat[2:3,4:5]

## Masking

In [251]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [252]:
id(mat)

1888731501776

In [253]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [261]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [131]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [132]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [133]:
mat[mat==50] 

array([50])

In [ ]:
mat

In [134]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
mat

In [ ]:
a1 = mat[mat<50] 
a1

In [ ]:
mat

In [ ]:
a2 = mat[mat>50] 
a2

In [ ]:
a3 = mat[mat<=50] 
a3

In [ ]:
a4 = mat[mat==50]
a4

# python program to generat otp 

In [135]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 5200


In [ ]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

In [ ]:
def wish():
    print('good even')
wish()

wish()

wish()

In [1]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000019E9C791080>


In [2]:
list1

['a', 'b', 'g', 1, 5]

In [ ]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)